// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.source.registration.entity;

import com.source.registration.entity.Members;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Members_Roo_Configurable {
    
    declare @type: Members: @Configurable;
    
}
