// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springroo.testgit.domain;

import com.springroo.testgit.domain.Register;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Register_Roo_Configurable {
    
    declare @type: Register: @Configurable;
    
}
